'use strict';
const el = id => document.getElementById(id);
const bytes = n => n == null ? 'Unknown' : (n / 1000000).toFixed(1) + ' MB';
const names = {capture_chunks:'Capture chunks',predictions:'Predictions',labels:'Outcomes & labels',boundary:'Prospective boundary',capture_status:'Capture status'};
function fail(message){el('error').textContent=message;el('error').hidden=false;}
async function api(url,options){const r=await fetch(url,{...options,cache:'no-store',credentials:'same-origin'});if(r.status===401){el('access').hidden=false;el('content').hidden=true;throw new Error('Open your private access link.');}if(!r.ok){let data;try{data=await r.json();}catch{throw new Error('The research service is unavailable.');}throw new Error(data.error||'Request failed.');}return r.json();}
function params(format='csv.gz'){const q=new URLSearchParams();for(const k of ['dataset','symbol'])q.set(k,el(k).value);if(el('dataset').value==='capture')q.set('stream',el('stream').value);for(const k of ['start','end']){const v=el(k).value;if(!v)throw new Error('Set the start and end time.');q.set(k,v+'Z');}q.set('format',format);return q;}
function busy(value){for(const id of ['estimate','gzip','csv'])el(id).disabled=value;}
async function estimate(){const data=await api('/research/api/estimate?'+params());el('estimate-result').textContent=data.compressed_input_bytes!=null?`${bytes(data.compressed_input_bytes)} compressed source · up to ${data.max_source_rows.toLocaleString()} records. CSV size varies.`:`About ${(data.estimated_rows||0).toLocaleString()} rows (planner estimate). Output size is capped during download.`;return data;}
async function download(format){busy(true);el('error').hidden=true;try{params(format);await estimate();const a=document.createElement('a');a.href='/research/api/download?'+params(format);a.download='';document.body.append(a);a.click();a.remove();el('estimate-result').textContent+=' Download requested; check your browser’s download list.';}catch(e){fail(e.message);}finally{busy(false);}}
el('filters').addEventListener('submit',e=>{e.preventDefault();download('csv.gz');});
el('csv').addEventListener('click',()=>download('csv'));
el('estimate').addEventListener('click',async()=>{busy(true);try{await estimate();}catch(e){fail(e.message);}finally{busy(false);}});
el('dataset').addEventListener('change',()=>{const d=el('dataset').value;el('stream-label').hidden=d!=='capture';el('symbol').disabled=['capture_status','boundary'].includes(d);el('clock-note').textContent=d==='labels'?'Labels use the linked prediction’s event clock, not label maturation time.':d==='boundary'?'The immutable boundary is exported regardless of selected time range.':d==='predictions'?'Predictions use the frozen event clock. Start included; end excluded.':'Capture selection uses original receipt time. Start included; end excluded.';});
async function init(){try{const fragment=new URLSearchParams(location.hash.slice(1));const token=fragment.get('access');if(location.hash)history.replaceState(null,'',location.pathname);if(token)await api('/research/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const data=await api('/research/api/status');el('content').hidden=false;el('size').textContent=bytes(data.database_bytes);el('version').textContent='Capture '+(data.schema_version||'unknown');const streams=data.streams||[];for(const s of streams){const o=document.createElement('option');o.value=s.name;o.textContent=s.name.replaceAll('_',' ');el('stream').append(o);}const times=streams.map(s=>s.latest).sort();const latest=times.at(-1);el('latest').textContent=latest?latest.slice(0,19).replace('T',' '):'No capture yet';el('range').textContent='From '+(streams.map(s=>s.start).sort()[0]||'unknown').slice(0,19).replace('T',' ');const c=data.session_counters||{};el('population').textContent=`${c.predictions??'—'} predictions · ${c.labels??'—'} labels`;const healthy=data.observer?.healthy??data.healthy;el('badge').textContent=data.preview?'Local preview · sample downloads':healthy===true?'Shadow observer healthy':healthy===false?'Observer needs attention':'Observer status unavailable';const end=latest?new Date(latest):new Date();el('end').value=end.toISOString().slice(0,19);el('start').value=new Date(end-300000).toISOString().slice(0,19);for(const [name,t]of Object.entries(data.tables)){const card=document.createElement('article');card.className='dataset';const title=document.createElement('strong');title.textContent=names[name]||name;const detail=document.createElement('span');detail.textContent=`${bytes(t.total_bytes)} · approximately ${(t.estimated_rows==null?'unknown':t.estimated_rows.toLocaleString())} rows`;card.append(title,detail);el('datasets').append(card);} }catch(e){el('badge').textContent='Protected research data';fail(e.message);}}
init();
